### ISSUE TITLE
Default admin set page throws an exception

### ISSUE THREAD

**Issue by anusharanganathan** [CottageLabs/willow#105]
URL: http://localhost:3000/admin/admin_sets/admin_set%2Fdefault
UI: Click on _Default admin set_ in home page or from administration -> administration sets -> Default Admin Set

Error 
```

ActionController::UrlGenerationError in Sufia::Admin::AdminSets#show

Showing /bundle/gems/sufia-7.3.0/app/views/kaminari/blacklight_compact/_paginator.html.erb where line #9 raised:

No route matches {:action=>"show", :controller=>"sufia/admin/admin_sets", :id=>"admin_set/default", :page=>nil, :q=>nil}
```

Stack trace
```
actionpack (5.0.1) lib/action_dispatch/journey/formatter.rb:51:in `generate'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:629:in `generate'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:660:in `generate'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:707:in `url_for'
actionpack (5.0.1) lib/action_dispatch/routing/url_for.rb:172:in `url_for'
actionview (5.0.1) lib/action_view/routing_url_for.rb:90:in `url_for'
kaminari (0.17.0) lib/kaminari/helpers/tags.rb:32:in `page_url_for'
kaminari_route_prefix (0.0.2) lib/kaminari_route_prefix/helpers/tags.rb:30:in `page_url_for'
kaminari (0.17.0) lib/kaminari/helpers/tags.rb:53:in `url'
kaminari (0.17.0) lib/kaminari/helpers/tags.rb:56:in `to_s'
actionview (5.0.1) lib/action_view/buffers.rb:12:in `<<'
sufia (7.3.0) app/views/kaminari/blacklight_compact/_paginator.html.erb:9:in `block in __bundle_gems_sufia_______app_views_kaminari_blacklight_compact__paginator_html_erb__2430820380209639681_70313891583440'
kaminari (0.17.0) lib/kaminari/helpers/paginator.rb:39:in `instance_eval'
kaminari (0.17.0) lib/kaminari/helpers/paginator.rb:39:in `render'
sufia (7.3.0) app/views/kaminari/blacklight_compact/_paginator.html.erb:8:in `__bundle_gems_sufia_______app_views_kaminari_blacklight_compact__paginator_html_erb__2430820380209639681_70313891583440'
actionview (5.0.1) lib/action_view/template.rb:159:in `block in render'
activesupport (5.0.1) lib/active_support/notifications.rb:166:in `instrument'
actionview (5.0.1) lib/action_view/template.rb:354:in `instrument'
actionview (5.0.1) lib/action_view/template.rb:157:in `render'
actionview (5.0.1) lib/action_view/renderer/partial_renderer.rb:343:in `render_partial'
actionview (5.0.1) lib/action_view/renderer/partial_renderer.rb:311:in `block in render'
actionview (5.0.1) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'
actionview (5.0.1) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
actionview (5.0.1) lib/action_view/renderer/partial_renderer.rb:310:in `render'
actionview (5.0.1) lib/action_view/renderer/renderer.rb:47:in `render_partial'
actionview (5.0.1) lib/action_view/renderer/renderer.rb:21:in `render'
actionview (5.0.1) lib/action_view/helpers/rendering_helper.rb:32:in `render'
kaminari (0.17.0) lib/kaminari/helpers/tags.rb:28:in `to_s'
kaminari (0.17.0) lib/kaminari/helpers/paginator.rb:100:in `to_s'
kaminari_route_prefix (0.0.2) lib/kaminari_route_prefix/helpers/action_view_extension.rb:22:in `paginate'
curation_concerns (1.7.6) app/views/collections/_paginate_compact.html.erb:1:in `__bundle_gems_curation_concerns_______app_views_collections__paginate_compact_html_erb__2523926672130277827_70313898586560'
actionview (5.0.1) lib/action_view/template.rb:159:in `block in render'
activesupport (5.0.1) lib/active_support/notifications.rb:166:in `instrument'
actionview (5.0.1) lib/action_view/template.rb:354:in `instrument'
actionview (5.0.1) lib/action_view/template.rb:157:in `render'
actionview (5.0.1) lib/action_view/renderer/partial_renderer.rb:343:in `render_partial'
actionview (5.0.1) lib/action_view/renderer/partial_renderer.rb:311:in `block in render'
actionview (5.0.1) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'
actionview (5.0.1) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
actionview (5.0.1) lib/action_view/renderer/partial_renderer.rb:310:in `render'
actionview (5.0.1) lib/action_view/renderer/renderer.rb:47:in `render_partial'
actionview (5.0.1) lib/action_view/renderer/renderer.rb:21:in `render'
actionview (5.0.1) lib/action_view/helpers/rendering_helper.rb:32:in `render'
sufia (7.3.0) app/views/sufia/admin/admin_sets/_sort_and_per_page.html.erb:3:in `__bundle_gems_sufia_______app_views_sufia_admin_admin_sets__sort_and_per_page_html_erb___2921082758144501298_70313820844480'
actionview (5.0.1) lib/action_view/template.rb:159:in `block in render'
activesupport (5.0.1) lib/active_support/notifications.rb:166:in `instrument'
actionview (5.0.1) lib/action_view/template.rb:354:in `instrument'
actionview (5.0.1) lib/action_view/template.rb:157:in `render'
actionview (5.0.1) lib/action_view/renderer/partial_renderer.rb:343:in `render_partial'
actionview (5.0.1) lib/action_view/renderer/partial_renderer.rb:311:in `block in render'
actionview (5.0.1) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'
actionview (5.0.1) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
actionview (5.0.1) lib/action_view/renderer/partial_renderer.rb:310:in `render'
actionview (5.0.1) lib/action_view/renderer/renderer.rb:47:in `render_partial'
actionview (5.0.1) lib/action_view/helpers/rendering_helper.rb:35:in `render'
sufia (7.3.0) app/views/sufia/admin/admin_sets/show.html.erb:46:in `__bundle_gems_sufia_______app_views_sufia_admin_admin_sets_show_html_erb__1808250800843570109_70313904938300'
actionview (5.0.1) lib/action_view/template.rb:159:in `block in render'
activesupport (5.0.1) lib/active_support/notifications.rb:166:in `instrument'
actionview (5.0.1) lib/action_view/template.rb:354:in `instrument'
actionview (5.0.1) lib/action_view/template.rb:157:in `render'
actionview (5.0.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
actionview (5.0.1) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'
actionview (5.0.1) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
actionview (5.0.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
actionview (5.0.1) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
actionview (5.0.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (5.0.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (5.0.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (5.0.1) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.0.1) lib/action_view/rendering.rb:103:in `_render_template'
actionpack (5.0.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (5.0.1) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (5.0.1) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.0.1) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (5.0.1) lib/abstract_controller/rendering.rb:26:in `render'
actionpack (5.0.1) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (5.0.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/local/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
activesupport (5.0.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (5.0.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
actionpack (5.0.1) lib/action_controller/metal/implicit_render.rb:36:in `default_render'
actionpack (5.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
actionpack (5.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `tap'
actionpack (5.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.1) lib/abstract_controller/base.rb:188:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.1) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.1) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (5.0.1) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.1) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.1) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.1) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
railties (5.0.1) lib/rails/engine.rb:522:in `call'
railties (5.0.1) lib/rails/railtie.rb:193:in `public_send'
railties (5.0.1) lib/rails/railtie.rb:193:in `method_missing'
actionpack (5.0.1) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
actionpack (5.0.1) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
warden (1.2.6) lib/warden/manager.rb:34:in `catch'
warden (1.2.6) lib/warden/manager.rb:34:in `call'
rack (2.0.1) lib/rack/etag.rb:25:in `call'
rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.1) lib/rack/head.rb:12:in `call'
rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
active-fedora (11.1.5) lib/active_fedora/ldp_cache.rb:26:in `call'
flipflop (2.3.1) lib/flipflop/feature_cache.rb:12:in `call'
activerecord (5.0.1) lib/active_record/migration.rb:553:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
railties (5.0.1) lib/rails/engine.rb:522:in `call'
rack (2.0.1) lib/rack/handler/webrick.rb:86:in `service'
/usr/local/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/usr/local/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/usr/local/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

**Comment by martyn-w** [comment]
👍  now working fine
