### ISSUE TITLE
Exception on willow-dev when creating a new work

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/willow#126]
After entering metadata, one file (an image), selecting 2 Collections to associate with and setting the item to Public, on Save this error:

```
STATUS: 500 java.lang.NullPointerException at org.modeshape.jcr.NodeTypes$AbstractNodeDefinitionSet.childDefinitionSatisfies(NodeTypes.java:2836) at org.modeshape.jcr.NodeTypes$AbstractNodeDefinitionSet.childDefinitionSatisfies(NodeTypes.java:2728) at org.modeshape.jcr.NodeTypes$AbstractNodeDefinitionSet.findBest(NodeTypes.java:2609) at org.modeshape.jcr.NodeTypes$MultipleNodeDefinitionSet.findBestDefinitionForChild(NodeTypes.java:2929) at org.modeshape.jcr.AbstractJcrNode.nodeDefinition(AbstractJcrNode.java:2909) at org.modeshape.jcr.AbstractJcrNode.getDefinition(AbstractJcrNode.java:2836) at org.modeshape.jcr.AbstractJcrNode.isCheckedOut(AbstractJcrNode.java:3223) at org.modeshape.jcr.AbstractJcrProperty.checkForCheckedOut(AbstractJcrProperty.java:210) at org.modeshape.jcr.AbstractJcrProperty.remove(AbstractJcrProperty.java:328) at org.fcrepo.kernel.modeshape.utils.NodePropertiesTools.removeNodeProperty(NodePropertiesTools.java:252) at org.fcrepo.kernel.modeshape.rdf.JcrRdfTools.remov...

Extracted source (around line #119):
117
118
119
120
121
122
              
    resp.tap do |resp|
      unless resp.status < 400
        raise case resp.status
          when 400
            if resp.env.method == :head
              # If the request was a HEAD request (which only retrieves HTTP headers),

Rails.root: /willow_source

Application Trace | Framework Trace | Full Trace
ldp (0.6.4) lib/ldp/client/methods.rb:119:in `block in check_for_errors'
ldp (0.6.4) lib/ldp/client/methods.rb:117:in `tap'
ldp (0.6.4) lib/ldp/client/methods.rb:117:in `check_for_errors'
ldp (0.6.4) lib/ldp/client/methods.rb:110:in `block in patch'
activesupport (5.0.1) lib/active_support/notifications.rb:166:in `instrument'
ldp (0.6.4) lib/ldp/client/methods.rb:102:in `patch'
active-fedora (11.1.5) lib/active_fedora/caching_connection.rb:29:in `patch'
/usr/local/lib/ruby/2.3.0/delegate.rb:83:in `method_missing'
active-fedora (11.1.5) lib/active_fedora/initializing_connection.rb:47:in `patch'
active-fedora (11.1.5) lib/active_fedora/sparql_insert.rb:11:in `execute'
active-fedora (11.1.5) lib/active_fedora/ldp_resource_service.rb:24:in `update'
active-fedora (11.1.5) lib/active_fedora/persistence.rb:204:in `execute_sparql_update'
active-fedora (11.1.5) lib/active_fedora/persistence.rb:184:in `_update_record'
active-fedora (11.1.5) lib/active_fedora/indexing.rb:70:in `_update_record'
active-fedora (11.1.5) lib/active_fedora/callbacks.rb:244:in `block in _update_record'
activesupport (5.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_update_callbacks'
active-fedora (11.1.5) lib/active_fedora/callbacks.rb:244:in `_update_record'
active-fedora (11.1.5) lib/active_fedora/persistence.rb:168:in `create_or_update'
active-fedora (11.1.5) lib/active_fedora/callbacks.rb:236:in `block in create_or_update'
activesupport (5.0.1) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.1) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_save_callbacks'
active-fedora (11.1.5) lib/active_fedora/callbacks.rb:236:in `create_or_update'
active-fedora (11.1.5) lib/active_fedora/persistence.rb:33:in `save!'
active-fedora (11.1.5) lib/active_fedora/validations.rb:56:in `save!'
active-fedora (11.1.5) lib/active_fedora/associations/indirectly_contains_association.rb:13:in `insert_record'
active-fedora (11.1.5) lib/active_fedora/associations/collection_association.rb:162:in `block (2 levels) in concat_records'
active-fedora (11.1.5) lib/active_fedora/associations/collection_association.rb:260:in `add_to_target'
active-fedora (11.1.5) lib/active_fedora/associations/collection_association.rb:161:in `block in concat_records'
active-fedora (11.1.5) lib/active_fedora/associations/collection_association.rb:159:in `each'
active-fedora (11.1.5) lib/active_fedora/associations/collection_association.rb:159:in `concat_records'
active-fedora (11.1.5) lib/active_fedora/associations/indirectly_contains_association.rb:9:in `concat'
active-fedora (11.1.5) lib/active_fedora/associations/collection_proxy.rb:856:in `<<'
curation_concerns (1.7.6) app/actors/curation_concerns/actors/add_to_collection_actor.rb:35:in `block in add_to_collections'
curation_concerns (1.7.6) app/actors/curation_concerns/actors/add_to_collection_actor.rb:33:in `each'
curation_concerns (1.7.6) app/actors/curation_concerns/actors/add_to_collection_actor.rb:33:in `add_to_collections'
curation_concerns (1.7.6) app/actors/curation_concerns/actors/add_to_collection_actor.rb:6:in `create'
curation_concerns (1.7.6) app/actors/curation_concerns/actors/actor_stack.rb:22:in `create'
sufia (7.3.0) app/actors/sufia/create_with_files_actor.rb:6:in `create'
curation_concerns (1.7.6) app/actors/curation_concerns/actors/actor_stack.rb:22:in `create'
sufia (7.3.0) app/actors/sufia/create_with_remote_files_actor.rb:6:in `create'
curation_concerns (1.7.6) app/actors/curation_concerns/actors/actor_stack.rb:22:in `create'
curation_concerns (1.7.6) app/actors/curation_concerns/actors/abstract_actor.rb:25:in `create'
curation_concerns (1.7.6) app/actors/curation_concerns/actors/actor_stack.rb:22:in `create'
curation_concerns (1.7.6) app/controllers/concerns/curation_concerns/curation_concern_controller.rb:47:in `create'
actionpack (5.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.1) lib/abstract_controller/base.rb:188:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.1) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.1) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (5.0.1) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.1) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.1) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.1) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
warden (1.2.6) lib/warden/manager.rb:34:in `catch'
warden (1.2.6) lib/warden/manager.rb:34:in `call'
rack (2.0.1) lib/rack/etag.rb:25:in `call'
rack (2.0.1) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.1) lib/rack/head.rb:12:in `call'
rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
active-fedora (11.1.5) lib/active_fedora/ldp_cache.rb:26:in `call'
flipflop (2.3.1) lib/flipflop/feature_cache.rb:12:in `call'
activerecord (5.0.1) lib/active_record/migration.rb:553:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
web-console (2.3.0) lib/web_console/middleware.rb:20:in `block in call'
web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
railties (5.0.1) lib/rails/engine.rb:522:in `call'
rack (2.0.1) lib/rack/handler/webrick.rb:86:in `service'
/usr/local/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/usr/local/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/usr/local/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
Request

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"KtcyoOi/E6/77WreRBK2YzCmbHaze5c5m2sVMWg4Ne84cXKqNVY5uWTGf14/iA/3LCMlhVzA2EE44tHN/JVDhQ==",
 "work"=>
  {"title"=>["The Title"],
   "creator"=>["Richard"],
   "keyword"=>["something"],
   "rights"=>["http://creativecommons.org/licenses/by/3.0/us/"],
   "contributor"=>[""],
   "description"=>[""],
   "publisher"=>[""],
   "date_created"=>[""],
   "subject"=>[""],
   "language"=>[""],
   "identifier"=>[""],
   "based_near"=>[""],
   "related_url"=>[""],
   "source"=>[""],
   "resource_type"=>[""],
   "admin_set_id"=>"admin_set/default",
   "collection_ids"=>["", "x920fw84d", "qb98mf449"],
   "visibility"=>"open",
   "visibility_during_embargo"=>"restricted",
   "embargo_release_date"=>"2017-04-22",
   "visibility_after_embargo"=>"open",
   "visibility_during_lease"=>"open",
   "lease_expiration_date"=>"2017-04-22",
   "visibility_after_lease"=>"restricted"},
 "uploaded_files"=>["7"],
 "new_user_name_skel"=>"",
 "new_user_permission_skel"=>"none",
 "new_group_name_skel"=>"Select a group",
 "new_group_permission_skel"=>"none",
 "agreement"=>"1"}
```

**Comment by richard-jones** [comment]
I was just able to successfully create a new work without associating it with any collections

**Comment by Nimphal** [comment]
Creating a work and associating with a collection seems to be working right now. Closing this.
