### ISSUE TITLE
Cannot start Rails console in container shell

### ISSUE THREAD

**Issue by Nimphal** [CottageLabs/willow#37]
~~After upgrading to Sufia 7.2 (though not necessarily related to the upgrade)~~ I have confirmed this is not related to the upgrade, as running it on master gives the same results, `rails console` throws this error in the willow container shell:

```
# rails console
Running via Spring preloader in process 447
/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:351:in `initialize!': Application has been already initialized. (RuntimeError)
	from /willow_source/config/environment.rb:5:in `<top (required)>'
	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /bundle/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
	from /bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
	from /bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:67:in `console'
	from /bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /bundle/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /willow_source/bin/rails:9:in `<top (required)>'
	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

I had the same problem when needing to run a generator, but went around it by throwing a sleep in the container startup before just before app initialisation and commenting out 

```ruby
# Initialize the Rails application.
Rails.application.initialize!
```
in config/environment.rb . I could probably do the same for my current console needs, but it is obviously an unsustainable approach, so we should look at fixing it.

We can probably blame https://github.com/rails/spring to some extent.

**Comment by Nimphal** [comment]
The commit that introduces this issue is baddf3f9d935c2890af7a95f46a23283499c1b77

**Comment by Nimphal** [comment]
It did turn out to be the preloader, Spring. I tried fixing it using https://github.com/jonleighton/spring-docker-example , but it wouldn't work without sharing the `tmp` directory and if that's shared, the rails server doesn't start on a subsequent `docker-compose up`. This is not to say that it is impossible to make it work, but it would require more juggling of directories and Spring configurations. Worth noting that Spring has only recently acquired support for this sort of thing so it may be easier if we do it later. The PR above disabled the preloader so that we can regain access to the console.
